CREATE DATABASE crudPHP; 

CREATE TABLE users (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(45),
email VARCHAR(45),
contato VARCHAR(45),
idade VARCHAR(3),
estado_civil INT(20),
STATUS TINYINT(2));

CREATE TABLE estado_civil(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;
descricao VARCHAR(45)
);